-- Run these scripts in the Supabase SQL Editor

-- 1. Create the Dazlance_basic_Info table
CREATE TABLE IF NOT EXISTS public."Dazlance_basic_Info" (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now(),
    session_id uuid NOT NULL, -- Used to link the 3 form steps
    "Full_name" text,
    "Display_name" text,
    "DOB" date,
    "Gender" text,
    "City" text,
    "Time_zone" text,
    "Address" text,
    "Job_title" text,
    "Tag_line" text,
    "Bio" text,
    "Experience" bigint,
    "Email" text,
    "Phone_number" text
);

-- 2. Create the requirements table
CREATE TABLE IF NOT EXISTS public."requirements" (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now(),
    session_id uuid NOT NULL,
    whatsapp text,
    discord text,
    github text,
    jira text,
    git boolean,
    nodejs boolean,
    "Antigravity" text
);

-- 3. Create the Finish table
CREATE TABLE IF NOT EXISTS public."Finish" (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now(),
    session_id uuid NOT NULL,
    "Work_capacity" text,
    "Time_zone" text,
    "Start_date" text,
    "Skills" text,
    "Experience_level" text,
    "Portfolio" text,
    "Payment_method" text,
    "Bank" text,
    "Account_no" text,
    "Branch_code" text,
    "Holder_name" text
);

-- Add indexes on session_id for fast retrieval of latest rows
CREATE INDEX IF NOT EXISTS idx_dazlance_basic_info_session ON public."Dazlance_basic_Info"(session_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_requirements_session ON public."requirements"(session_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_finish_session ON public."Finish"(session_id, created_at DESC);

-- Enable RLS on all tables
ALTER TABLE public."Dazlance_basic_Info" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."requirements" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Finish" ENABLE ROW LEVEL SECURITY;

-- Create policies for anonymous/authenticated access
-- Since session_id is our custom tracker, we allow INSERT and SELECT for everyone.
-- WARNING: In a production app with real users, you should map this to auth.uid().
-- We are exclusively inserting new rows (no UPDATE enabled).

-- Dazlance_basic_Info Policies
CREATE POLICY "Allow public insert to basic info" ON public."Dazlance_basic_Info"
    FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public select from basic info" ON public."Dazlance_basic_Info"
    FOR SELECT USING (true);

-- requirements Policies
CREATE POLICY "Allow public insert to requirements" ON public."requirements"
    FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public select from requirements" ON public."requirements"
    FOR SELECT USING (true);

-- Finish Policies
CREATE POLICY "Allow public insert to finish" ON public."Finish"
    FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public select from finish" ON public."Finish"
    FOR SELECT USING (true);
